language: node_js
node_js:
  - '6'
before_install:
  - npm i -g npm@latest
install:
  - yarn install
script:
  - yarn test
cache: yarn
deploy:
  provider: npm
  email: ammmze@gmail.com
  api_key:
    secure: Lgy1Bdr+v46YMhifuwajlL+BH6KzpvtWLOUCly5/xnJLAhiIVA0M2TNs7o05WGeB8mzCncGA9EdXCT2FRnzt72G1Mheefk1juT+CGo0bFOFlg5NGvsw2CjwHRNToGeCiecejaKsmJWfUridpuMSAT1xEbrWozXH1agXdCvAv3DokvuyEzWvGAGFdcm1RqrGGXQVS7mSHmg9dCwrZJGCTmVhtjOSUYxFHZePXkoyrvKbdTYKMKQ7j+TC9z4bVFAMMkuMMS2ZNKzGWrrzk5nnPSyns/LoKWkIwOGk31JC1SMwvhqc0LfuRo0bq/BW9ma86PybS8Ol+ZgyJQ6sjHwAhs7fPwnYm1poqZsWN1oi8xyxNgpoJ+LWQZcsUYgBpGmFHa0//uJwmA9ARZ3OrJmh/5aa8WhjGNQ/HqDqQuLoirWkPbtUyXr+XHgDLMaKWuIgq2SFnvCrqZuR6qLUwDkTf7s596aq+wKvTayKmXiJkCC8A026sHfLLSCzKPDPzdL2AcAzWX72B8GUu8DW25Jl0a45XwRrM4y4SBXBxxBtrfAdiy/qaiR+SpVPgXOiWZw5O3xyQYAC9l/O2Pp8b3JDYrh/tlJH2wOdaGo988IbAIU7r304TDi4Yym/DBFySY8Vla/flWNQU29IogQFIbnXi/7ztohk+sLRa2PiN9hiR6Ck=
  on:
    tags: true
    repo: MashupMill/enzyme-adapter-react-register
